### ISSUE TITLE
Node 10 and greater support?

### ISSUE THREAD

**Issue by DavideDaniel** [slimapi/apib2json#8]
Is there a plan to support this module further? Currently due to the dependency on protagonist this tool is not useable in CIs running with Node LTS 10 and above. If protagonist is to remain a hard dependency either this module needs updating protagonist or decoupling from it. If there is no plan to support further versions of node then we should include a engine restriction in the package.json to prevent installs and throw an error when node version is greater than the supported version.

**Comment by o5** [comment]
PR will be accepted ;)

**Comment by o5** [comment]
https://github.com/slimapi/apib2json/pull/10
